# Generated by Django 2.2 on 2020-04-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
